### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by xbanki** [xbanki/xbanki-me#12]
Before I create any other content, I would like to implement a viewport size aware navigation bar with the following components:

 - Two buttons:
   - Menu Button - Opens up a side menu on the right-hand side
   - Settings Button - Opens a dropdown menu which displays a list of radio settings
 - Logo that animates between "routes"

## Notes ##

All of these items should be responsive. I'm envisioning a nesting menu system that expands depending on what item you clicked on, as a pseudo routing system. 

## To-Do ##

 - [x] Implement Navbar elements & styles
 - [x] Implement the following Menu Button logic:
   - [x] Implement Menu Button elements & styles
   - [x] Implement Anime.js based animations
   - [x] Implement state-aware `activate_button`
   - [x] Implement event emitter which gets called by `activate_button` that takes in to account the current button state
 - [x] Implement the following Menu Panel logic:
   - [x] Implement Menu Panel elements & styles
   - [x] Implement Anime.js based animations
   - [x] Implement an event consumer to open & close the panel based on Menu Button state
 - [x] Implement the following Logo logic:
   - [x] Implement Logo elements & styles
   - [x] Implement Anime.js based animations`route` variable
